users/urls.py
#url for users
from django.conf.urls import url
from django.contrib.auth.views import LoginView

from . import views

app_name='users'
urlpatterns = [
    url(r'^login/$',LoginView.as_view(template_name='users/login.html'),name='login'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^register/$',views.register,name='register'),
    ]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect as HRR
from django.urls import reverse
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.forms import UserCreationForm 

# Create your views here.
def logout_view(request):
    logout(request)
    return HRR(reverse('learning_logs:index'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request,authenticated_user)
            return HRR(reverse('learning_logs:index'))
    context = {'form':form}
    return render(request,'users/register.html',context)

users/templates/users/login.html
{%extends 'learning_logs/base.html'%}
{% load bootstrap3%}

{% block header %}
  <h2>Log in to your account</h2>
{% endblock header%}

{% block content %}  
  <form method='post' action="{% url 'users:login'%}" class="form">
    {%csrf_token%}
    {% bootstrap_form form%}
    
    {% buttons %}
      <button name="submit" class="btn btn-primart">log in</button>
    {% endbuttons %}
   <input type='hidden' name='next' value="{% url 'learning_logs:index' %}"/>
  </form>
{%endblock content%}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Register a new account.</h2>
{% endblock header %}

{% block content%}
  <form action="{% url 'users:register'%}" method="post" class="form">
    {%csrf_token%}
    {% bootstrap_form form%}
    {% buttons %}
      <button name="submit" class="btn btn-primary">register</button>
      <input type="hidden" name="next" value={% url 'learning_logs:index' %} />
    {% endbuttons %}
  </form>
{%endblock content%}